---
abstract: 'OASIS WSS Signatures'
author:
  - 'Mark Overmeer'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Compile-WSS-Signature
no_index:
  directory:
    - t
    - inc
requires:
  Crypt::OpenSSL::RSA: 0
  Crypt::OpenSSL::X509: 1.803
  Digest: 0
  Digest::HMAC_SHA1: 0
  Digest::SHA1: 0
  Encode: 0
  File::Basename: 0
  File::Glob: 0
  File::Slurp: 0
  Log::Report: 0.92
  MIME::Base64: 0
  Scalar::Util: 0
  Test::More: 0.54
  XML::Compile: 1.29
  XML::Compile::C14N: 0.93
  XML::Compile::Cache: 0.995
  XML::Compile::SOAP: 2.33
  XML::Compile::WSS: 1.09
  XML::LibXML: 2.00
version: 2.01
