---
abstract: 'OASIS WSS Signatures'
author:
  - 'Mark Overmeer'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Compile-WSS-Signature
no_index:
  directory:
    - t
    - inc
requires:
  Crypt::OpenSSL::RSA: 0
  Crypt::OpenSSL::X509: 0
  Digest: 0
  Encode: 0
  File::Basename: 0
  File::Slurp: 0
  Log::Report: 0.92
  MIME::Base64: 0
  Test::More: 0.54
  XML::Compile: 1.29
  XML::Compile::C14N: 0.90
  XML::Compile::Cache: 0.992
  XML::Compile::SOAP: 2.33
  XML::Compile::WSS: 1.04
version: 0.91
