=head1 NAME

XML::Compile::WSS::SecToken::X509v3 - WSS Security Token X509v3 style

=head1 INHERITANCE

 XML::Compile::WSS::SecToken::X509v3
   is a XML::Compile::WSS::SecToken

=head1 SYNOPSIS

  # Most verbose
  my $certfn = 'cert.pem';
  my $cert   = Crypt::OpenSSL::X509->new_from_file($certfn);
  my $token  = XML::Compile::WSS::SecToken::X509v3->new
    ( id          => 'some-wsu-id'
    , certificate => $cert
    );
  $wss->sigature(token => $token, ...);

  # Shortest
  $wss->signature(token => $cert, ...);

  # More syntax
  my $token = XML::Compile::WSS::SecToken->new
    ( type        => XTP10_X509v3
    , id          => 'some-wsu-id'
    , certificate => $cert
    );

  my $token = XML::Compile::WSS::SecToken::X509v3
    ->fromFile($cert_fn, format => FORMAT_ASN1);

=head1 DESCRIPTION

Use an X509 certificate as security token.

CPAN lists a few modules which wrap a X509 certificate, for the
moment only Crypt::OpenSSL::X509 is supported, patches for other
implementations are welcomed.

See F<docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0.pdf>

=head2 Supported token types

=head2 Not supporter (yet)

=head1 METHODS

=over 4

=item XML::Compile::WSS::SecToken::X509v3-E<gt>B<fromFile>(FILENAME, OPTIONS)

[1.07] read the certificate from a file.  You can pass all OPTIONS provided
by L<new()|XML::Compile::WSS::SecToken::X509v3/"METHODS"> plus some specific parameters.

 -Option--Default
  format  FORMAT_PEM

=over 2

=item format => FORMAT_*

The file format is not always auto-detected, so you may need to
provide it explicition.  The constants are exported by Crypt::OpenSSL::X509

=back

=back

=head2 Constructors

=over 4

=item XML::Compile::WSS::SecToken::X509v3-E<gt>B<fromBinSecToken>(WSS, DATA)

See L<XML::Compile::WSS::SecToken/"Constructors">

=item XML::Compile::WSS::SecToken::X509v3-E<gt>B<fromConfig>(CONFIG, OPTIONS)

See L<XML::Compile::WSS::SecToken/"Constructors">

=item XML::Compile::WSS::SecToken::X509v3-E<gt>B<new>(OPTIONS)

Either the C<certificate> object or a C<cert_file> must be specified.

 -Option     --Defined in                 --Default
  binary       XML::Compile::WSS::SecToken  undef
  certificate                               undef
  id           XML::Compile::WSS::SecToken  'my-token'
  type         XML::Compile::WSS::SecToken  XTP10_X509v3

=over 2

=item binary => BYTES

=item certificate => CERTIFICATE

=item id => wsu::Id

=item type => TOKENTYPE

=back

=back

=head2 Attributes

=over 4

=item $obj-E<gt>B<certificate>()

=item $obj-E<gt>B<id>()

See L<XML::Compile::WSS::SecToken/"Attributes">

=item $obj-E<gt>B<type>()

See L<XML::Compile::WSS::SecToken/"Attributes">

=back

=head2 Handlers

=over 4

=item $obj-E<gt>B<asBinary>()

See L<XML::Compile::WSS::SecToken/"Handlers">

=item $obj-E<gt>B<makeBinSecTokenWriter>(WSS)

See L<XML::Compile::WSS::SecToken/"Handlers">

=back

=head1 SEE ALSO

This module is part of XML-Compile-WSS-Signature distribution version 1.09,
built on January 18, 2013. Website: F<http://perl.overmeer.net/xml-compile/>

Other distributions in this suite:
L<XML::Compile>,
L<XML::Compile::SOAP>,
L<XML::Compile::SOAP12>,
L<XML::Compile::SOAP::Daemon>,
L<XML::Compile::SOAP::WSA>,
L<XML::Compile::C14N>,
L<XML::Compile::WSS>,
L<XML::Compile::WSS::Signature>,
L<XML::Compile::Tester>,
L<XML::Compile::Cache>,
L<XML::Compile::Dumper>,
L<XML::Compile::RPC>,
L<XML::Rewrite>,
L<XML::eXistDB>,
and
L<XML::LibXML::Simple>.

Please post questions or ideas to the mailinglist at
F<http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/xml-compile>

For live contact with other developers, visit the C<#xml-compile> channel
on C<irc.perl.org>.

=head1 LICENSE

Copyrights 2012-2013 by [Mark Overmeer]. For other contributors see ChangeLog.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.
See F<http://www.perl.com/perl/misc/Artistic.html>

